name: Firebase Test Lab

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build APK
      run: ./gradlew assembleDebug

    - name: Authenticate with Firebase
      env:
        FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
      run: |
        echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > $HOME/firebase-key.json
        firebase login:ci --token $(firebase auth:token --json-file=$HOME/firebase-key.json)

    - name: Upload APK to Firebase Test Lab
      run: |
        firebase test android run --app app/build/outputs/apk/debug/app-debug.apk --device model=Pixel2,version=28 --test lab/test-scenario
